on:
    - push

name: Tests

jobs:
    test:
        name: Run NodeJS Tests
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Setup Java
                uses: actions/setup-java@v1
                with:
                    java-version: 16
            -   name: Run Gradle Tests
                run: ./gradlew jsTest --stacktrace
            -   name: Deploy report to Github Pages
                if: always()
                uses: peaceiris/actions-gh-pages@v2
                env:
                    PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    PUBLISH_BRANCH: gh-pages
                    PUBLISH_DIR: build/reports/test/jsTest

